name: Deploy backend to Azure Container Apps

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend-aca.yml"
  workflow_dispatch:

env:
  RG: rg-vibluna
  ACA_ENV: env-vibluna
  ACA_APP: vibluna-api
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}   # e.g. vibluna.azurecr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy to Container Apps (build + push + deploy)
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ env.RG }}
          containerAppName: ${{ env.ACA_APP }}
          environment: ${{ env.ACA_ENV }}
          dockerfilePath: backend/Dockerfile
          buildContext: ./backend
          imageToBuild: ${{ env.ACR_LOGIN_SERVER }}/vibluna-api:${{ github.sha }}
          registryUrl: ${{ env.ACR_LOGIN_SERVER }}
          registryUsername: ${{ secrets.ACR_USERNAME }}
          registryPassword: ${{ secrets.ACR_PASSWORD }}
          ingress: external
          targetPort: 8000
          envVars: |
            SECRET_KEY=supersecret
            CREATOR_INVITE_CODE=restrict
            CORS_ORIGINS=*
