name: deploy-frontend-storage
on:
  workflow_dispatch: {}
permissions: { id-token: write, contents: read }
jobs:
  upload-static-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with: { creds: ${{ secrets.AZURE_CREDENTIALS }} }
      - name: Enable Static Website
        run: |
          az storage blob service-properties update             --account-name "${{ secrets.STORAGE_ACCOUNT }}"             --static-website --index-document index.html
      - name: Upload frontend files to $web
        run: |
          az storage blob upload-batch             -s frontend             -d '$web'             --account-name "${{ secrets.STORAGE_ACCOUNT }}"             --auth-mode key             --account-key "${{ secrets.STORAGE_KEY }}"
      - name: Show website endpoint
        run: az storage account show -n "${{ secrets.STORAGE_ACCOUNT }}" --query "primaryEndpoints.web" -o tsv
