name: Deploy frontend to Azure Storage Static Website

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend-storage.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Uses Azure CLI without needing azure/login because we pass account key
      - name: Enable static website & upload index.html
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob service-properties update \
              --account-name "${{ secrets.STORAGE_ACCOUNT }}" \
              --account-key "${{ secrets.STORAGE_KEY }}" \
              --static-website --index-document index.html

            az storage blob upload \
              --account-name "${{ secrets.STORAGE_ACCOUNT }}" \
              --account-key "${{ secrets.STORAGE_KEY }}" \
              --container-name '$web' \
              --name index.html \
              --file frontend/index.html \
              --overwrite
